CREATE TABLE Temporal(
    NombreVictima VARCHAR2(200),
    ApellidoVictima VARCHAR2(200),
    DireccionVictima VARCHAR2(200),
    FechaPrimera_Sospecha DATE,
    FechaConfirmacion DATE,
    FechaMuerte DATE,
    EstadoVictima VARCHAR2(200),
    NombreAsociado VARCHAR2(200),
    ApellidoAsociado VARCHAR2(200),
    FechaConocio DATE,
    ContactoFisico VARCHAR2(200),
    FechaInicioContacto DATE,
    FechaFinContacto DATE,
    NombreHospital VARCHAR2(200),
    DireccionHospital VARCHAR2(200),
    UbicacionVictima VARCHAR2(200),
    FechaLlegada DATE,
    FechaRetiro DATE,
    Tratamiento VARCHAR2(200),
    Efectividad NUMBER,
    FechaInicioTratamiento DATE,
    FechaFinTratamiento DATE,
    EfectividadEnVictima NUMBER
)